on:
  workflow_call:
    inputs:
      branch:
        description: The branch to run this on
        type: string
        required: true
        
jobs:
  release-tag-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
          release_branches: ${{ inputs.branch }}
          dry_run: true
