on:
  workflow_call:

jobs:
  release-tag-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
          release_branches: ${{ github.ref_name }}
          dry_run: true
  completed:
    needs: release-tag-dry-run
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Tests completed # Needed because matrix tests have dynamic workflow names based on the folder name. This is something we cannot make a required test from.
        run: echo "All tests completed"