name: Update latest Major Version

on:
  workflow_call:
    inputs:
      new_tag:
        description: The tag or reference to use as input for releasing latest major version from
        type: string
        required: true

jobs:
  retagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get major version number
        id: major_version
        run: echo major_version=$(echo "${{ inputs.new_tag }}" | cut -c1) >> $GITHUB_OUTPUT
      - name: Tag new target
        run: git tag -f v${{ steps.major_version.outputs.major_version }} ${{ inputs.new_tag }}
      - name: Push new tag
        run: git push origin v${{ steps.major_version.outputs.major_version }} --force
