on:
  workflow_call:
    inputs:
      actionlint_flags:
        description: The branch to run this on
        type: string
        required: false
        default: ''
      level:
        description: The branch to run this on
        type: string
        required: false
        default: 'error'
      fail_on_error:
        description: The branch to run this on
        type: boolean
        required: false
        default: true
  
jobs:
    reviewdog:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        pull-requests: write
      steps:
        - uses: actions/checkout@v4
        - uses: reviewdog/action-actionlint@v1
          with:
            reporter: github-pr-review
            level: ${{ inputs.level }}
            fail_on_error: ${{ inputs.fail_on_error }}
            actionlint_flags: ${{ inputs.actionlint_flags }}
