on:
  workflow_call:
    inputs:
      actionlint_flags:
        description: 'actionlint flags. (actionlint -oneline <actionlint_flags>)'
        type: string
        required: false
        default: ''
      level:
        description: 'Report level for reviewdog [info,warning,error]. It is same as -level flag of reviewdog.'
        type: string
        required: false
        default: 'error'
      fail_level:
        description: 'If set to none, always use exit code 0 for reviewdog. Otherwise, exit code 1 for reviewdog if it finds at least 1 issue with severity greater than or equal to the given level. Possible values: [none, any, info, warning, error]'
        type: string
        required: false
        default: error
  
jobs:
    reviewdog:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        pull-requests: write
      steps:
        - uses: actions/checkout@v5
        - uses: reviewdog/action-actionlint@v1
          with:
            reporter: github-pr-review
            level: ${{ inputs.level }}
            fail_level: ${{ inputs.fail_level }}
            actionlint_flags: ${{ inputs.actionlint_flags }}
