on:
  workflow_call:

concurrency:
  group: release

jobs:
  merge-into-master:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: git merge into master
        run: |
          git switch master
          git merge -m "Release new version" ${{ github.ref_name }}
          git push
