name: Update latest Major Version

on:
  workflow_call:

jobs:
  release-tag-major:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ""
        release_branches: ${{ github.ref_name }}
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
    - name: Get major version number
      id: major_version
      run: echo major_version=$(echo "${{ steps.tag_version.outputs.new_tag }}" | cut -c1) >> $GITHUB_OUTPUT
    - name: Tag new target
      run: git tag -f v${{ steps.major_version.outputs.major_version }} ${{ steps.tag_version.outputs.new_tag }}
    - name: Push new tag
      run: git push origin v${{ steps.major_version.outputs.major_version }} --force
