name: Release

on:
  push:
    branches:
      - master

jobs:
  # release new tag for the workflow
  release-module-version:
    uses: ./.github/workflows/github-release-tag-update-latest-major.yaml
    permissions:
      contents: write
