name: Release

on:
  push:
    branches:
      - master

jobs:
  # release new tag for the workflow
  release-module-version:
    uses: guidion-digital/release-workflows/.github/workflows/github-release-tag-update-latest-major.yaml@1.0.2
    permissions:
      contents: write
