name: Release

on:
  push:
    branches:
      - master

jobs:
  release-tag:
    uses: ./.github/workflows/github-release-tag.yaml

  retagging:
    needs: release-tag
    uses: ./.github/workflows/github-release-tag-update-latest-major.yaml
    permissions:
      contents: write
    with:
      new_tag: ${{ needs.release-tag.outputs.new_tag }}
