name: Test

on:
  pull_request:
    types: 
      - opened
      - edited
      - synchronize
    branches:
      - master

jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    permissions:
      # contents: read
      # checks: write
      # issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-review
          fail_on_error: true

  release-dry-run:
    needs: reviewdog
    uses: ./.github/workflows/github-release-tag-dry-run.yaml
