name: Test

on:
  pull_request:
    types: 
      - opened
      - edited
      - synchronize
    branches:
      - master

jobs:
  test-workflow:
    uses: ./.github/workflows/github-test-workflow.yaml
    permissions:
      pull-requests: write

  test-release-tag:
    needs: test-workflow
    uses: ./.github/workflows/github-release-tag-dry-run.yaml
    with:
      branch: acc
