name: Test

on:
  pull_request:
    types: 
      - opened
      - edited
      - synchronize
    branches:
      - master

jobs:
  # actions:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         submodules: true
  #     - name: Install action-validator with asdf
  #       uses: asdf-vm/actions/install@v3
  #       with:
  #         tool_versions: |
  #           action-validator 0.5.1
  #     - name: Lint Actions
  #       run: |
  #         find .github/workflows -type f \( -iname \*.yaml -o -iname \*.yml \) \
  #           | xargs -I {} action-validator --verbose {}

  nektos-act:
    # needs: actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install nix
        run: |
          echo y | curl -L https://nixos.org/nix/install | sh -s -- --daemon
      - name: Install act
        run: |
          nix-env -iA nixpkgs.act
      - name: Type act
        run: |
          type act
      - name: Run act
        run: |
          act

  # release-dry-run:
  #   needs: nektos-act
  #   uses: ./.github/workflows/github-release-tag-dry-run.yaml
