name: Test

on:
  pull_request:
    types: 
      - opened
      - edited
      - synchronize
    branches:
      - master

jobs:
  release-dry-run:
    uses: ./.github/workflows/github-release-tag-dry-run.yaml
