name: Test

on:
  pull_request:
    types: 
      - opened
      - edited
      - synchronize
    branches:
      - master

jobs:
  reviewdog:
    uses: ./.github/workflows/github-test-workflow.yaml
    permissions:
      pull-requests: write

  release-dry-run:
    needs: reviewdog
    uses: ./.github/workflows/github-release-tag-dry-run.yaml
    with:
      branch: acc
